-- MySQL Script generated by MySQL Workbench
-- Sat Dec 14 18:21:34 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dog_breeding
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dog_breeding
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dog_breeding` DEFAULT CHARACTER SET utf8 ;
USE `dog_breeding` ;

-- -----------------------------------------------------
-- Table `dog_breeding`.`litter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`litter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sire_id` INT NOT NULL,
  `dam_id` INT NOT NULL,
  `birthdate` DATE NOT NULL,
  `birthplace` VARCHAR(135) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_litter_dog_idx` (`sire_id` ASC) VISIBLE,
  INDEX `fk_litter_dog1_idx` (`dam_id` ASC) VISIBLE,
  CONSTRAINT `fk_litter_dog`
    FOREIGN KEY (`sire_id`)
    REFERENCES `dog_breeding`.`dog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_litter_dog1`
    FOREIGN KEY (`dam_id`)
    REFERENCES `dog_breeding`.`dog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dog_breeding`.`dog`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`dog` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `litter_id` INT NULL,
  `name` VARCHAR(45) NOT NULL,
  `gender` TINYINT NOT NULL,
  `breed` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dog_litter1_idx` (`litter_id` ASC) VISIBLE,
  CONSTRAINT `fk_dog_litter1`
    FOREIGN KEY (`litter_id`)
    REFERENCES `dog_breeding`.`litter` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dog_breeding`.`vet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`vet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dog_breeding`.`health_record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`health_record` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `dog_id` INT NOT NULL,
  `vet_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_health_record_dog1_idx` (`dog_id` ASC) VISIBLE,
  INDEX `fk_health_record_vet1_idx` (`vet_id` ASC) VISIBLE,
  CONSTRAINT `fk_health_record_dog1`
    FOREIGN KEY (`dog_id`)
    REFERENCES `dog_breeding`.`dog` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_health_record_vet1`
    FOREIGN KEY (`vet_id`)
    REFERENCES `dog_breeding`.`vet` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dog_breeding`.`health_problem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`health_problem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `health_record_id` INT NOT NULL,
  `problem` VARCHAR(135) NOT NULL,
  `date` DATE NOT NULL,
  `treatment` VARCHAR(135) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_health_problem_health_record1_idx` (`health_record_id` ASC) VISIBLE,
  CONSTRAINT `fk_health_problem_health_record1`
    FOREIGN KEY (`health_record_id`)
    REFERENCES `dog_breeding`.`health_record` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dog_breeding`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dog_breeding`.`token_blacklist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dog_breeding`.`token_blacklist` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `jti` VARCHAR(255) NOT NULL,
  `expiration` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `jti_UNIQUE` (`jti` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
